### ISSUE TITLE
Wiki little error

### ISSUE THREAD

**Issue by Rubylium** [corazon2/FiveM-CCore#3]
![image](https://user-images.githubusercontent.com/19718604/77048582-fd293a00-69c6-11ea-93e6-892eb4d0d33e.png)
Little error on the wiki

Leaving a while without any Wait / Citizen.Wait will lead to a client crash / freeze for everyone who do not have the police job. ( Pretty sure you did know that, just a mistake )
![image](https://user-images.githubusercontent.com/19718604/77048929-7d4f9f80-69c7-11ea-9e20-9b1f7a0ab286.png)

Code but with broken indentation because fuck github logic
```lua
local playerJob = getPlayerJob()

Citizen.CreateThread(function()
	while true do
		if playerJob == "police" then
			local charID = getCharID()
			local salary = <salary amount>

	 		Citizen.Wait(25000)
            TriggerServerEvent("corazon_core:functionAddBank", charID, salary)
        else
            Citizen.Wait(1000)
		end
	end
end)
```
Should fix it.

**Comment by corazon2** [comment]
it's good, it's corrected, thanks to you :)
